name: Build and Deploy node Express app to azure
on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: "nodeanand"    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "Application"      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '8.11.1'                # set this to the node version to use
  RESOURCEGROUPNAME: "nodeanand-rg"
  LOCATION: "South Central US"
  HOSTINGPLANNAME: "nodeanand-plan"
  APPINSIGHTLOCATION: "South Central US"
  SKU: "S1 Standard"

jobs:
  FunctionalTests:
    name: Run Functional tests
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    # Run functional tests
    - name: Run Functional tests
      continue-on-error: false
      run: |
        cd Application
        npm install
        cd ../Tests
        npm install
        $Path = $env:TEMP; $Installer = "chrome_installer.exe"; Invoke-WebRequest "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile $Path$Installer; Start-Process -FilePath $Path$Installer -Args "/silent /install" -Verb RunAs -Wait; Remove-Item $Path$Installer
        Invoke-WebRequest https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_win32.zip -outFile chromedriver.zip
        Expand-Archive -Path chromedriver.zip
        Remove-Item chromedriver.zip
        gulp functionaltest --webAppUrl https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/
